<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-JKE8LG9E" failures="1" tests="2" name="Test" time="38.103" errors="0" timestamp="2022-07-26T19:22:34 IST">
  <testcase classname="com.qa.testLayer.TestCase1" name="buyOrder" time="8.617">
    <failure type="java.lang.AssertionError" message="expected [Oder Created successfully] but found [Order Created successfully]">
      <![CDATA[java.lang.AssertionError: expected [Oder Created successfully] but found [Order Created successfully]
at com.qa.testLayer.TestCase1.buyOrder(TestCase1.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- buyOrder -->
  <testcase classname="com.qa.testLayer.TestCase1" name="sellOrder" time="9.608"/>
</testsuite> <!-- Test -->
